### ISSUE TITLE
FPKGi 11.02+ support?

### ISSUE THREAD

**Issue by iCankat** [ItsJokerZz/FPKGi#26]
I’m running FPKGi on PS4 11.02+, and after the first launch the app completely freezes. All files exist under /data/FPKGi/ except config.json, which is never created. The app shows the version and name at the top and buttons at the bottom, but nothing responds. I’ve tried manually creating config and JSON files, but it doesn’t help.

This clearly isn’t a content issue—the app simply doesn’t work on 11.02 and above. Please add support for 11.02+ because right now it’s completely unusable.

**Comment by ItsJokerZz** [comment]
Should work as-is on any firmware, nothing in the app is firmware dependent and should be fine as low as 5.05 and newer, but just that alone dont help me, can you provide the logs @ `/data/UnityOrbisBridge.log`?

**Comment by iCankat** [comment]
> Should work as-is on any firmware, nothing in the app is firmware dependent and should be fine as low as 5.05 and newer, but just that alone dont help me, can you provide the logs @ `/data/UnityOrbisBridge.log`?

09/04/2025 @ 09:33:59AM [INFO] Initiating native dialogs...

The log file you mentioned only contains this. /data/UnityOrbisBridge.log 

There’s nothing else. Your application launches but no button inputs work. We can only press the PS button to send it to the background. Your application name is shown in the top-left corner. Other than that, there’s no response at all. As I mentioned in the FTP directory, the folder /data/FPKGi has been created, and inside it there are the folders Backgrounds, ContentJSONs, Downloads. However, the config.json file is missing. I tried adding a config.json file I found online and compiled myself, but it was in vain.

**Comment by ItsJokerZz** [comment]
```
09/05/2025 @ 04:01:20PM [INFO] Initiating native dialogs...
09/05/2025 @ 04:01:21PM [DEBUG] Displaying content and system information...
09/05/2025 @ 04:01:21PM [DEBUG] Checking for app updates...
09/05/2025 @ 04:01:21PM [DEBUG] Fetching latest MD5 hash to compare...
09/05/2025 @ 04:01:22PM [DEBUG] Latest MD5: e7a9b4f68156c8204041edf9c85c21d2
09/05/2025 @ 04:01:22PM [DEBUG] Current MD5: 8408a3177fc0b6485dd6672eb180420a
09/05/2025 @ 04:01:22PM [DEBUG] Checking for the latest version available...
09/05/2025 @ 04:01:23PM [DEBUG] Latest Version: ?.??.?
09/05/2025 @ 04:01:23PM [DEBUG] Current Version: 1.00.1
09/05/2025 @ 04:01:23PM [DEBUG] Build Number: 0006
```
Not too sure then tbh should show something like this just fine as I mentioned, nothing is FW dependant. What version of the app are you using and have you tried others?

**Comment by Buzbee** [comment]
I am having a similar issue with PS4 v12.02, GoldHEN v2.4b18.6 and FPKGv1.01.0.

After installing it goes to a black screen or to the background image with a notification to connect to the internet or use local files. Nothing works after that. I have an internet connection with Al-Azif's dns servers. I also have a working Node.js server accessible with the PS4 web browser. The config.json is populated like

"games": "http://192.168.1.xxx:8080/GAMES.json",

Not sure what is wrong. 

I also had issues with it creating the config.json through Goldhens package installer. I believe using the pkg installer in debug settings got it finally created.

**Comment by DefKorns** [comment]
@Buzbee  https://github.com/ItsJokerZz/FPKGi/issues/30#issuecomment-3299538332

**Comment by ItsJokerZz** [comment]
@Buzbee, the installation wont cause the issue, it was an oversight on my part that I've just fixed and will get out ASAP. Not sure what @iCankat's issue is as others on even newer firmware than 11.02 aren't having FW related issues, but this may fix their issue.

**Comment by ItsJokerZz** [comment]
Just pushed!

**Comment by Buzbee** [comment]
The fix still shows a notification to connect to the internet or use local files. I have an internet connection with Al-Azif's dns servers.

**Comment by ItsJokerZz** [comment]
> The fix still shows a notification to connect to the internet or use local files. I have an internet connection with Al-Azif's dns servers. 

No idea then to be honest, that will only happen if it cannot connect to GitHub.com, just to check for internet- for toggling "Populate Via Web" off and it can just be toggled back on. It may just be removable, I'd have to check. If I remember correctly it was added to fix loading with "Populate Via Web" being toggled while not having an internet connection would cause lag and/or crash the app on launch. I'll look into it and if possible just remove it, but it shouldn't affect anything at all.
